COMMON_FLAGS="-march=native -O3 -flto=thin -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -Wl,-O3 -Wl,--thinlto-jobs=12"

PORTAGE_NICENESS="10"

LD="ld.lld"
CC="clang"
CXX="clang++"
CPP="clang-cpp"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

RUSTFLAGS="-C target-cpu=native -C opt-level=3"

MAKEOPTS="-j12 -l13"
EMERGE_DEFAULT_OPTS="--jobs 4 --load-average 13"

FEATURES="candy parallel-fetch parallel-install"

ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"

USE="X dbus llvm clang lto jit"

LC_MESSAGES=C.UTF-8
L10N="ru"

INPUT_DEVICES="libinput"
VIDEO_CARDS="amdgpu radeonsi"
CPU_FLAGS_X86="aes avx avx2 avx_vnni bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3 vpclmulqdq"
GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="https://mirror.yandex.ru/gentoo-distfiles/"
